version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "28090:80"
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=snortyAdmin
    volumes:
      - mongo-data:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d:ro
volumes:
  mongo-data:
