const mongoose = require("mongoose");
const { Schema } = mongoose;

const AlertSchema = new Schema({
  tags: [String],
  flow_id: { type: Number, required: true },
  community_id: String,
  path: String,
  type: String,
  packet_info: {
    linktype: Number,
  },
  vlan: [Number],
  timestamp: Date,
  stream: Number,
  dest_ip: String,
  dest_port: Number,
  src_ip: String,
  pkt_src: String,
  in_iface: String,
  payload_printable: String,
  "@timestamp": Date,
  alert: {
    gid: Number,
    action: String,
    severity: Number,
    metadata: {
      former_category: [String],
      attack_target: [String],
      signature_severity: [String],
      updated_at: [String],
      created_at: [String],
      deployment: [String],
      affected_product: [String],
    },
    signature: String,
    rev: Number,
    category: String,
    signature_id: Number,
  },
  host: String,
  proto: String,
  flow: {
    dest_ip: String,
    pkts_toserver: Number,
    bytes_toserver: Number,
    start: Date,
    bytes_toclient: Number,
    src_ip: String,
    dest_port: Number,
    pkts_toclient: Number,
    src_port: Number,
  },
  src_port: Number,
  payload: String,
  capture_file: String,
  packet: String,
  geoip: Object,
  direction: String,
  event_type: String,
  "@version": String,
  showPayload: Boolean,
  editMode: Boolean,
  showSearchContext: Boolean,
  commentary: String,
  confirmDelete: Boolean,
  showActionsContext: Boolean,
  done: Boolean,
  toDo: String,
});

const SELKSAlert = mongoose.model("SELKSAlert", AlertSchema);

module.exports = SELKSAlert;
